src/main/java/ssd/SSD.java
src/test/java/ssd/SSDTest.java

- SSD 에 관한 테스트 작성
---
---
- SSD 관한 테스트 코드 작성 (READ/WRITE 기능 및 예외) 추가
---
- TDD 방식으로 FAIL 문만 처리
---
- 관련 이슈는 없음
---

SSD 테스트 생성

---

src/main/java/ssd/SSD.java

- SSD Write 기능 추가했습니다. 
---
---
- SSD 생성자 추가와 Write 기능 추가
---
- Write 관련 Exception 확인 및 Write 시 생성된 파일 확인 완료
---
- close #10
- ref #5
---

[feature]makeWriteMethod

---

META-INF/MANIFEST.MF
src/main/java/shell/TestShell.java

- TestShell 에 help, exit 기능 구현, 
- TestShell 에 SSD를 직접 호출하는 로직 삭제
---
---
- TestShell에서 main 함수 실행 시 launchShell 동작하도록 구현
- While(True)에서 While(isRunning)으로 빼고, isRunning을 생성자에서 true로 설정
---
---
- close #10
- ref #5
---

'apply_exit_help'

---

.gitignore
src/main/java/ssd/SSD.java
src/main/resources/META-INF/MANIFEST.MF
src/test/java/shell/TestShellTest.java
src/test/java/shell/TestShell_exit_help_test.java

- SSD의 Main 부분, Read 함수 구현
---
---
- Main: Command 처리
- Main: Command별 parameter에 대한 invalid 처리
- Read: Invalid LBA 처리
- Read 후 ssd_output.txt로 결과 입력
---
- Main 예외 테스트 4개 통과
- Read Invalid parameter 테스트 2개 통과 (lba가 음수 혹은 100이상)
- Read 정상여부 테스트의 경우 Write -> Read로 테스트 하여 Write 구현 후 확인 가능
---
- 
---

[feature] main/read

---

src/test/java/shell/FullWriteFullReadTest.java

- shell의 fullwrite와 fullread에 대한 unit test를 생성하였습니다. 
---
---
- fullwrite 시 writeSBA가 100번 호출되었는지 확인
- fullread 시 readSBA가 100번 호출되고 올바른 값이 읽혔는지 확인
---
---
- close #10
- ref #5
---

FullWriteFullReadTest_RED_상태_unit_test

---

src/main/java/shell/TestShell.java

- SSD jar파일을 호출하는 함수 추가
---
---
- ProcessBuilder 클래스를 사용하여, jar파일을 실행하고, 리턴되는 결과물을 가져오는 로직
---
- 테스트 케이스 전체 변경 필요
---
- jar파일의 경로를 C: 에 두어야 함

[feature] read, write 시스템콜 추가

---

src/main/java/shell/TestShell.java

- 시스템콜 하는 쪽 버그 수정
- 경로문제와 파라미터 통신 문제로 인한 버그 해결
---
---
---
---
- close #10
- ref #5
---

[test] 시스템 콜 부분 상대경로로 변경

---

build.gradle.kts
src/main/java/shell/TestShell.java

---
---
---
---
- close #10
- ref #5
---

Build Jar File Name Fix

---

src/main/java/shell/TestShell.java
src/test/java/shell/TestShellScenarioTest.java

[Fix] Shell/feature Read 로직 변경
---
---
---
---
- close #10
- ref #5
---

[fix] full 함수 변경

---

src/main/java/shell/TestShell.java

- 결과값 읽는 과정 중 띄워쓰기와 줄바꿈으로 인한 에러 확인 
---
---
---
---
- close #10
- ref #5
---

[fix] trim(), \n으로 인한 테스트 시나리오 에러 확인

---

src/main/java/shell/TestShell.java
src/test/java/shell/TestShellTest.java

---
---
---
---
- close #10
- ref #5
---

[test] 테스트 유닛테스트 수정

---

src/main/java/ssd/command/Command.java
src/main/java/ssd/command/CommandExecutor.java
src/main/java/ssd/command/EraseCommand.java
src/main/java/ssd/command/FlushCommand.java
src/main/java/ssd/command/ReadCommand.java
src/main/java/ssd/command/WriteCommand.java
src/main/java/ssd/logic/SSDCommandLogic.java

- command 패턴 추가 및 클래스 생성
---
---
- command 패턴으로 분리해서 클래스를 생성 시켰습니다.
---
- shell helper 부분은 미통과
---
---

[refatoring] command 패턴 추가

---

src/main/java/shell/Command.java
src/main/java/shell/CommandExecutor.java
src/main/java/shell/Document.java
src/main/java/shell/EraseCommand.java
src/main/java/shell/ReadCommand.java
src/main/java/shell/ScenarioCommand.java
src/main/java/shell/TestShell.java
src/main/java/shell/WriteCommand.java

- SSD 실행을 위한 ProcessBuilder read/write 일부 통합
- Command Pattern으로 리팩토링을 위한 파일 생성
- 기타 단순 리팩토링
---
---
---
---
- close #10
- ref #5
---

[refacotring] process 실행 분리, Command Pattern을 위한 파일 생성, 기타 refactoring

---

src/main/java/ssd/SSD.java
src/main/java/ssd/buffer/BufferFileManager.java
src/main/java/ssd/buffer/CommandBuffer.java
src/main/java/ssd/command/Command.java
src/main/java/ssd/command/CommandExecutor.java
src/main/java/ssd/command/CommandType.java
src/main/java/ssd/command/EraseCommand.java
src/main/java/ssd/command/FlushCommand.java
src/main/java/ssd/command/ReadCommand.java
src/main/java/ssd/command/WriteCommand.java
src/main/java/ssd/common/ValidCheck.java
src/main/java/ssd/logic/SSDCommandLogic.java
src/test/java/ssd/SSDTest.java
src/test/java/ssd/logic/SSDCommandLogicTest.java

- AppLogic 과 CommandLogic 통합
- SSD 테스트 코드 전반적으로 수정
---
---
- SSD command 로직에 대해서 전반적으로 리팩토링을 진행하였습니다.
---
- SSD 관련 테스트는 PASS
---
---

[refactoring] AppLogic 클래스 삭제 및 테스트 코드 수정 및 전체적인 리팩토링

---

src/main/java/ssd/command/EraseCommand.java
src/test/java/shell/TestShell_erase.java

- shell design pattern 변경에 따른 unit test 변경
- sdd erase invalid 로직 수정
---
---
- erase 99 1 에 대해 error 처리하고 있는 부분에 대한 경계값 체크 로직 수정
- unit test 에러 나지 않도록 수정
---
- TestShell_erase 7개 테스트 PASS
---
- close #10
- ref #5
---

[refactor] design patterns 변경에 따른 error 발생하는 erase unit test 변경

---

src/main/java/shell/TestShell.java
src/main/java/shell/command/Document.java
src/main/java/shell/command/FlushCommand.java
src/main/java/shell/util/SSDCaller.java
src/test/java/shell/TestShell_flush.java
src/test/java/shell/util/TestShell_flush.java

- flush 기능 구현
---
---
- flush 명령을 받았을 때 SSD로 'F' 명령 전달
---
- TestShell_flush 정상 통과 (PASS)
---
---

[feature] shell Flush 기능 추가

---

src/main/java/shell/util/Logger.java
src/test/java/shell/util/LoggerTest.java

- Logger Print 기능 추가
---
---
- Runner mode일 시 sysout 출력 금지 / Runner Mode아닐 때만 sysout 실행
---
- Logger test 수행 완료
---
- close #10
- ref #5
---

[feature]Logger Print 기능 추가

---

src/test/java/shell/TestShellTest.java

---
TestShellTest Case별 Unit Test동작하도록 변경했습니다. 
- [ O] 테스트 코드 작성 및 통과 (JUnit5 + Mockito)
---
---변경된 로직에 맞게 TestShellTest Case별 Unit Test동작하도록 변경했습니다. 
---
- close #10
- ref #5
---

TestShellTest에러 안나게 수정했습니다.

---

src/main/java/ssd/command/BufferUtil.java
src/test/java/ssd/command/BufferUtilTest.java

---
---
---
---
- close #10
- ref #5
---

[feature] 버퍼 최적화 알고리즘 기능 추가

---

src/main/java/shell/util/TestScenario.java
src/test/java/shell/TestScenarioTest.java

- scenario4 unit test 추가 및 기존 unit test 1,2,3 수정
---
---
- write, erase, readcompare를 호출하는 횟수를 기반으로 unit test 수정
---
- PASS
---
- close #10
- ref #5
---

[test] scenario4 unit test 추가 및 기존 unit test 1,2,3 수정

---

src/main/java/shell/TestShell.java
src/main/java/shell/util/TestScenario.java
src/test/java/shell/TestScenarioTest.java

- scenario4 작성
---
---
- erase에 대한 검증 진행
---
---
- close #10
- ref #5
---

[feature] shell_scenario4_생성

---

src/test/java/shell/TestShell_read.java
src/test/java/shell/TestShell_write.java

- 하나로 된 read, write 파일을 구분
---
---
---
---
- close #10
- ref #5
---

[test] shell에서 readwrite 파일 구분 후 fullread, fullwrite 작성

---

src/test/java/shell/TestShell_exit_help_test.java

---
TestShell_Exit_Help_test 에러 발생 부분 수정했습니다. 
- [ O] 테스트 코드 작성 및 통과 (JUnit5 + Mockito)
---
---
TestShell_Exit_Help_test 에러 발생 부분 수정했습니다. 
---
- close #10
- ref #5
---

TestShell_Exit_Help_test 에러 발생 부분 수정했습니다. 

---

src/test/java/shell/TestShell_read.java
src/test/java/shell/TestShell_write.java

---
---
---
---
- close #10
- ref #5
---

[refactoring]testcase

---

src/main/java/shell/TestShell.java
src/main/java/shell/command/CommandExecutor.java
src/main/java/shell/command/Document.java
src/main/java/shell/command/FlushCommand.java
src/main/java/shell/util/Runner.java
src/test/java/shell/TestScenarioTest.java
src/test/java/shell/TestShell_read.java
src/test/java/shell/TestShell_write.java
src/test/java/shell/util/LoggerTest.java

- shell log 추가
---
---
---
---
- close #10
- ref #5
---

[refactoring] add more log

---

src/main/java/ssd/IO/BufferFileIO.java
src/main/java/ssd/buffer/CommandBuffer.java
src/main/java/ssd/buffer/SSDArgument.java

SSDArgument 생성자 추가
BufferFileIo 에서 폴더 구조를 포함한 filePath를 저장하는것으로 변경
---
---
---
---
- close #10
- ref #5
---

[refactor] 임시 저장 변수 buffer 제거 및 함수 변경
